package com.psx.prime360ClientService.serviceImpl;
 
public class SQLNegativeQueries {
    public static final String[] BATCH_NEG_QUERY_OF_EOD = {
            "INSERT INTO PSX_NEGATIVEAREA_BASE(AREA,AREA_ID,AREA_UNQ_ID,BATCHID,CITY,DUIFLAG,EVENTTYPE,INSERT_TIME,LCHGTIME,ORG,PIN,PSX_AREA,PSX_BATCH_ID,SEGMENT,STATE)"
                    + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            "select AREA,AREA_ID,AREA_UNQ_ID,BATCHID,CITY,DUIFLAG,EVENTTYPE,INSERT_TIME,LCHGTIME,ORG,PIN,PSX_AREA,PSX_BATCH_ID,SEGMENT,STATE from PSX_NEGATIVEAREA_BASE",
            "INSERT INTO PSX_NEGATIVE_BASE_AUDIT(AREA,AREA_ID,AREA_UNQ_ID,BATCHID,CITY,DUIFLAG,EVENTTYPE,INSERT_TIME,LCHGTIME,ORG,PIN,PSX_AREA,PSX_BATCH_ID,SEGMENT,STATE)"
                    + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            "SELECT * FROM PSX_NEGATIVEAREA_BASE WHERE UPPER(CITY) IN\n"
                    + "(SELECT UPPER(CITY) FROM PSX_NEGATIVEAREA_BASE WHERE PSX_BATCH_ID=?) AND \n"
                    + "ORG IN (SELECT ORG FROM PSX_NEGATIVEAREA_BASE WHERE PSX_BATCH_ID=?) AND PSX_BATCH_ID!=?",
            "INSERT INTO PSX_NEGATIVEAREA_BASE_HIST(AREA,AREA_ID,AREA_UNQ_ID,BATCHID,CITY,DUIFLAG,EVENTTYPE,INSERT_TIME,LCHGTIME,ORG,PIN,PSX_AREA,PSX_BATCH_ID,SEGMENT,STATE)"
                    + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            "DELETE FROM PSX_NEGATIVEAREA_BASE WHERE UPPER(CITY) IN(SELECT UPPER(CITY) FROM PSX_NEGATIVEAREA_BASE WHERE PSX_BATCH_ID=?) AND \n"
                    + "ORG IN (SELECT ORG FROM PSX_NEGATIVEAREA_BASE WHERE PSX_BATCH_ID=?) AND PSX_BATCH_ID!=?"
 
    };
}