package com.psx.prime360ClientService.serviceImpl;
 
public class SQLQueries {
 
    public static final String[] BATCH_QUERY_OF_EOD = {
        "INSERT INTO PSX_COMMON_STAGING_T(CUST_UNQ_ID,SOURCE_SYS_ID,"
                + "DATA_SOURCE_NAME,NAME,GENDER,DOB1,PAN,DRIVINGLIC,"
                + "AADHAAR,VOTERID,DATE_OF_INCORPORATION,TAN_NO,PROCESS_TYPE,"
                + "APPLICANT_TYPE,EMPLOYER_NAME,FATHER_NAME,PASSPORT,IFSC_CODE,"
                + "ACCOUNT_NUMBER,CREDIT_CARD_NUMBER,CIN,DIN,REGISTRATION_NO,"
                + "CONSTITUTION,CA_NUMBER,AGREEMENT_NUMBER,REMARKS,PERMANENT_ADDRESS,"
                + "PERMANENT_CITY,PERMANENT_PIN,PERMANENT_STATE,PERMANENT_STREET_NUMBER,LANDMARK,"
                + "OFFICE_ADDRESS,OFFICE_CITY,OFFICE_PIN,OFFICE_STATE,OFFICE_STREET_NUMBER,RESIDENCE_PHONE,"
                + "PERMANENT_PHONE,MOBILE,STD,CONTACT_EMAIL,PSX_ID,PSX_BATCH_ID,DUIFLAG,LCHGTIME,INSERT_TIME,CUSTOMER_ID,SEGMENT,SOURCE_SYSTEM,CUSTOMER_NO,DAY,MONTH,YEAR,ENTITY_SOURCE,DOI,FIRSTNAME,MIDDLENAME,LASTNAME)"
                + "values(?,?,?,?,?,to_date(?,'dd-mm-yyyy'),?,?,?,?,to_date(?,'dd-mm-yyyy'),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
};
}